import { DisplayNamesConfig } from './types/display-names-config.type';

export const DISPLAY_NAMES_CONFIG: DisplayNamesConfig = {
  robots: {
    displayName: 'מכונית',
    pluralDisplayName: 'מכוניות',
    columns: {
      id: { label: 'מזהה רובוט', parserFieldName: 'robot_UUID' },
      cardboardId: { label: 'מזהה קרטון', parserFieldName: 'cardboard_UUID' },
      sensorId: { label: 'מזהה חיישן', parserFieldName: 'sensor_UUID' },
      communicationId: { label: 'מזהה תקשורת', parserFieldName: 'communication_UUID' },
      saleId: { label: 'מזהה מכירה', parserFieldName: 'sale_UUID' },
      wiringId: { label: 'מזהה כבל', parserFieldName: 'wiring_UUID' },
      notes: { label: 'הערות', parserFieldName: 'notes' },
      source: { label: 'מקור', parserFieldName: 'source' },
    },
  },
  sensors: {
    displayName: 'חיישן',
    pluralDisplayName: 'חיישנים',
    columns: {
      id: { label: 'מזהה חיישן', parserFieldName: 'sensor_UUID' },
      sensorType: { label: 'סוג חיישן', parserFieldName: 'sensor_type' },
      sensorVersion: { label: 'גרסת חיישן', parserFieldName: 'sensor_version' },
      notes: { label: 'הערות', parserFieldName: 'notes' },
      source: { label: 'מקור', parserFieldName: 'source' },
    },
  },
  wirings: {
    displayName: 'חיווט',
    pluralDisplayName: 'כבלים',
    columns: {
      id: { label: 'מזהה כבל', parserFieldName: 'wiring_UUID' },
      wiringType: { label: 'סוג כבל', parserFieldName: 'wiring_type' },
      district: { label: 'מחוז', parserFieldName: 'district' },
      municipality: { label: 'עיריה', parserFieldName: 'municipality' },
      storageId: { label: 'מזהה אחסון', parserFieldName: 'storage_UUID' },
      notes: { label: 'הערות', parserFieldName: 'notes' },
      source: { label: 'מקור', parserFieldName: 'source' },
    },
  },
  storages: {
    displayName: 'אחסון',
    pluralDisplayName: 'אחסון',
    columns: {
      id: { label: 'מזהה אחסון', parserFieldName: 'storage_UUID' },
      storageType: { label: 'סוג אחסון', parserFieldName: 'storage_type' },
      storageVersion: { label: 'גרסת אחסון', parserFieldName: 'storage_version' },
      isStockNetanya: { label: 'מלאי נתניה', parserFieldName: 'is_stock_netanya' },
      isStockAfula: { label: 'מלאי עפולה', parserFieldName: 'is_stock_afula' },
      notes: { label: 'הערות', parserFieldName: 'notes' },
      source: { label: 'מקור', parserFieldName: 'source' },
    },
  },
  communications: {
    displayName: 'תקשורת',
    pluralDisplayName: 'תקשורת',
    columns: {
      id: { label: 'מזהה תקשורת', parserFieldName: 'communication_UUID' },
      communicationType: { label: 'סוג תקשורת', parserFieldName: 'communication_type' },
      plasticId: { label: 'מזהה פלסטיק', parserFieldName: 'plastic_UUID' },
      ironId: { label: 'מזהה ברזל', parserFieldName: 'iron_UUID' },
      notes: { label: 'הערות', parserFieldName: 'notes' },
      source: { label: 'מקור', parserFieldName: 'source' },
    },
  },
  plastics: {
    displayName: 'פלסטיק',
    pluralDisplayName: 'פלסטיקים',
    columns: {
      id: { label: 'מזהה פלסטיק', parserFieldName: 'plastic_UUID' },
      plasticType: { label: 'סוג פלסטיק', parserFieldName: 'plastic_type' },
      batteryId: { label: 'מזהה סוללה', parserFieldName: 'battery_UUID' },
      notes: { label: 'הערות', parserFieldName: 'notes' },
      source: { label: 'מקור', parserFieldName: 'source' },
    },
  },
  batteries: {
    displayName: 'סוללה',
    pluralDisplayName: 'סוללות',
    columns: {
      id: { label: 'מזהה סוללה', parserFieldName: 'battery_UUID' },
      sku: { label: 'מק"ט', parserFieldName: 'sku' },
      batteryType: { label: 'סוג סוללה', parserFieldName: 'battery_type' },
      batteryVersion: { label: 'גרסת סוללה', parserFieldName: 'battery_version' },
      lithiumVersion: { label: 'גרסת ליתיום', parserFieldName: 'lithium_version' },
      notes: { label: 'הערות', parserFieldName: 'notes' },
      source: { label: 'מקור', parserFieldName: 'source' },
    },
  },
  irons: {
    displayName: 'ברזל',
    pluralDisplayName: 'ברזלים',
    columns: {
      id: { label: 'מזהה ברזל', parserFieldName: 'iron_UUID' },
      ironType: { label: 'סוג ברזל', parserFieldName: 'iron_type' },
      ironVersion: { label: 'גרסת ברזל', parserFieldName: 'iron_version' },
      isHeatConductor: { label: 'מוליך חום', parserFieldName: 'is_heat_conductor' },
      notes: { label: 'הערות', parserFieldName: 'notes' },
      source: { label: 'מקור', parserFieldName: 'source' },
    },
  },
  cardboards: {
    displayName: 'קרטון',
    pluralDisplayName: 'קרטונים',
    columns: {
      id: { label: 'מזהה קרטון', parserFieldName: 'cardboard_UUID' },
      cardboardType: { label: 'סוג קרטון', parserFieldName: 'cardboard_type' },
      cardboardVersion: { label: 'גרסת קרטון', parserFieldName: 'cardboard_version' },
      notes: { label: 'הערות', parserFieldName: 'notes' },
      source: { label: 'מקור', parserFieldName: 'source' },
    },
  },
  sales: {
    displayName: 'מכירה',
    pluralDisplayName: 'מכירות',
    columns: {
      id: { label: 'מזהה מכירה', parserFieldName: 'sale_UUID' },
      carrier: { label: 'ספק שילוח', parserFieldName: 'carrier' },
      onlineStoreName: { label: 'שם חנות מקוונת', parserFieldName: 'online_store_name' },
      salesperson: { label: 'איש מכירות', parserFieldName: 'salesperson' },
      isPurchased: { label: 'נרכש', parserFieldName: 'is_purchased' },
      isStockAshdod: { label: 'מלאי אשדוד', parserFieldName: 'is_stock_ashdod' },
      isStockTelAviv: { label: 'מלאי תל אביב', parserFieldName: 'is_stock_tel_aviv' },
      isStockRehovot: { label: 'מלאי רחובות', parserFieldName: 'is_stock_rehovot' },
      dataSource: { label: 'מקור נתונים', parserFieldName: 'data_source' },
      notes: { label: 'הערות', parserFieldName: 'notes' },
      source: { label: 'מקור', parserFieldName: 'source' },
    },
  },
};
