version: "3.9"

services:
  parser:
    build:
      context: ./app/parser
      dockerfile: .docker/Dockerfile
    container_name: buster-parser-dev
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    expose:
      - "8000"
    volumes:
      - ./app/parser:/app
      - shared-tmp:/tmp
    networks:
      - buster-net
    restart: unless-stopped

  server:
    build:
      context: ./app/server
      dockerfile: .docker/Dockerfile.dev
    container_name: buster-server-dev
    expose:
      - "3000"
    env_file:
      - ./app/server/.env
    volumes:
      - ./app/server:/app
      - server_node_modules:/app/node_modules
      - shared-tmp:/tmp
    networks:
      - buster-net
    depends_on:
      - parser
    restart: unless-stopped

  client:
    build:
      context: ./app
      dockerfile: client/.docker/Dockerfile.dev
    container_name: buster-client-dev
    ports:
      - "4200:4200"
    volumes:
      - ./app/client:/app/client
      - client_node_modules:/app/client/node_modules
      - ./app/shared:/app/shared
    networks:
      - buster-net
    depends_on:
      - server
    restart: unless-stopped

volumes:
  shared-tmp:
    driver: local
  server_node_modules:
  client_node_modules:

networks:
  buster-net:
    driver: bridge
