FROM node:22.14.0
WORKDIR /app/client
COPY client/package.json client/package-lock.json ./
RUN npm ci
COPY client/ .
COPY shared/ /app/shared/
EXPOSE 4200
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--proxy-config", "proxy.conf.docker.json"]
