export const ALLOWED_TABLES = new Set([
  'robots',
  'sensors',
  'wirings',
  'communications',
  'batteries',
  'storages',
  'irons',
  'plastics',
  'cardboards',
]);

export const ALLOWED_COLUMNS: Record<string, Set<string>> = {
  robots: new Set([
    'id',
    'cardboardId',
    'sensorId',
    'communicationId',
    'wiringId',
    'carrier',
    'isPurchased',
    'district',
    'storeName',
    'isStockAshdod',
    'isStockTelAviv',
    'isStockRehovot',
    'isStockNetanya',
    'isStockAfula',
  ]),
  sensors: new Set(['id', 'sensorType', 'sensorVersion']),
  wirings: new Set(['id', 'wiringType', 'district', 'storeName', 'storageId']),
  communications: new Set(['id', 'communicationType', 'plasticId', 'ironId']),
  batteries: new Set([
    'id',
    'sku',
    'batteryType',
    'batteryVersion',
    'lithiumVersion',
    'batteryName',
    'salesPerson',
    'isStockTelAviv',
    'isStockRehovot',
  ]),
  storages: new Set(['id', 'storageType', 'storageVersion', 'isStockNetanya', 'isStockAfula']),
  irons: new Set(['id', 'ironType', 'ironVersion', 'heatConductor', 'isStockAshdod']),
  plastics: new Set(['id', 'plasticType', 'batteryId']),
  cardboards: new Set(['id', 'cardboardType', 'cardboardVersion']),
};
