export const HOME_LABEL_MAP = {
  resultsFound: 'נמצאו',
  results: 'תוצאות',
  selectTable: 'בחר טבלה',
  manageColumns: 'ניהול עמודות',
  exportExcel: 'ייצוא לאקסל',
} as const;

export const COLUMN_LABEL_MAP: Record<string, string> = {
  id: 'מזהה',
  cardboardId: 'מזהה קרטון',
  sensorId: 'מזהה חיישן',
  communicationId: 'מזהה תקשורת',
  saleId: 'מזהה מכירה',
  wiringId: 'מזהה כבל',
  storageId: 'מזהה אחסון',
  plasticId: 'מזהה פלסטיק',
  ironId: 'מזהה ברזל',
  batteryId: 'מזהה סוללה',
  sensorType: 'סוג חיישן',
  sensorVersion: 'גרסת חיישן',
  wiringType: 'סוג כבל',
  district: 'מחוז',
  municipality: 'עיריה',
  communicationType: 'סוג תקשורת',
  sku: 'מק"ט',
  batteryType: 'סוג סוללה',
  batteryVersion: 'גרסת סוללה',
  lithiumVersion: 'גרסת ליתיום',
  storageType: 'סוג אחסון',
  storageVersion: 'גרסת אחסון',
  isStockNetanya: 'מלאי נתניה',
  isStockAfula: 'מלאי עפולה',
  ironType: 'סוג ברזל',
  ironVersion: 'גרסת ברזל',
  isHeatConductor: 'מוליך חום',
  plasticType: 'סוג פלסטיק',
  cardboardType: 'סוג קרטון',
  cardboardVersion: 'גרסת קרטון',
  carrier: 'ספק שילוח',
  onlineStoreName: 'שם חנות מקוונת',
  salesperson: 'איש מכירות',
  isPurchased: 'נרכש',
  isStockAshdod: 'מלאי אשדוד',
  isStockTelAviv: 'מלאי תל אביב',
  isStockRehovot: 'מלאי רחובות',
  dataSource: 'מקור נתונים',
};
