export const HOME_LABEL_MAP = {
  resultsFound: 'נמצאו',
  results: 'תוצאות',
  selectTable: 'בחר טבלה',
  manageColumns: 'ניהול עמודות',
  exportExcel: 'ייצוא לאקסל',
} as const;

export const COLUMN_LABEL_MAP: Record<string, string> = {
  'robots.id': 'מזהה',
  'robots.cardboardId': 'מזהה קרטון',
  'robots.sensorId': 'מזהה חיישן',
  'robots.communicationId': 'מזהה תקשורת',
  'robots.saleId': 'מזהה מכירה',
  'robots.wiringId': 'מזהה כבל',
  'wirings.id': 'מזהה',
  'wirings.wiringType': 'סוג כבל',
  'wirings.district': 'מחוז',
  'wirings.municipality': 'עיריה',
  'wirings.storageId': 'מזהה אחסון',
  'storages.id': 'מזהה',
  'storages.storageType': 'סוג אחסון',
  'storages.storageVersion': 'גרסת אחסון',
  'storages.isStockNetanya': 'מלאי נתניה',
  'storages.isStockAfula': 'מלאי עפולה',
  'sensors.id': 'מזהה',
  'sensors.sensorType': 'סוג חיישן',
  'sensors.sensorVersion': 'גרסת חיישן',
  'communications.id': 'מזהה',
  'communications.communicationType': 'סוג תקשורת',
  'communications.plasticId': 'מזהה פלסטיק',
  'communications.ironId': 'מזהה ברזל',
  'plastics.id': 'מזהה',
  'plastics.plasticType': 'סוג פלסטיק',
  'plastics.batteryId': 'מזהה סוללה',
  'batteries.id': 'מזהה',
  'batteries.sku': 'מק"ט',
  'batteries.batteryType': 'סוג סוללה',
  'batteries.batteryVersion': 'גרסת סוללה',
  'batteries.lithiumVersion': 'גרסת ליתיום',
  'irons.id': 'מזהה',
  'irons.ironType': 'סוג ברזל',
  'irons.ironVersion': 'גרסת ברזל',
  'irons.isHeatConductor': 'מוליך חום',
  'cardboards.id': 'מזהה',
  'cardboards.cardboardType': 'סוג קרטון',
  'cardboards.cardboardVersion': 'גרסת קרטון',
  'sales.id': 'מזהה',
  'sales.carrier': 'ספק שילוח',
  'sales.onlineStoreName': 'שם חנות מקוונת',
  'sales.salesperson': 'איש מכירות',
  'sales.isPurchased': 'נרכש',
  'sales.isStockAshdod': 'מלאי אשדוד',
  'sales.isStockTelAviv': 'מלאי תל אביב',
  'sales.isStockRehovot': 'מלאי רחובות',
  'sales.dataSource': 'מקור נתונים',
};
